variables:
  DOCKER_IMAGE: example-pipeline
  DOCKER_REGISTRY: public.ecr.aws/bitswan
  DOCKER_HOST: tcp://docker:2375

build:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  only:
    - main
  before_script:
    - amazon-linux-extras install docker
    - yum install -y git
    - aws --version
    - docker --version
  script:
    - YEAR=$(date +%Y)
    - COMMIT_HASH=$(git rev-parse --short HEAD)
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$YEAR-$CI_PIPELINE_IID-git-$COMMIT_HASH .
    - docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE:$YEAR-$CI_PIPELINE_IID-git-$COMMIT_HASH $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$YEAR-$CI_PIPELINE_IID-git-$COMMIT_HASH
